AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scribe32 - AI Medical Scribe Backend

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

  DeepgramApiKey:
    Type: String
    NoEcho: true
    Description: Deepgram API Key for speech-to-text

  ExistingUserPoolId:
    Type: String
    Description: The ID of the existing Cognito User Pool (e.g., us-west-2_xxxxxx)

  ExistingUserPoolClientId:
    Type: String
    Description: The ID of the existing Cognito App Client

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        NOTES_TABLE: !Ref DentalScribeNotesTable
        USERS_TABLE: !Ref UsersTable
        PATIENTS_TABLE: !Ref PatientsTable
        TEMPLATES_TABLE: !Ref TemplatesTable
        DEEPGRAM_SECRET_ARN: !Ref DeepgramSecret
        USER_POOL_ID: !Ref ExistingUserPoolId
    Tracing: Active

Resources:
  # ========================================
  # DYNAMODB - Data Storage
  # ========================================
  DentalScribeNotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DentalScribeNotes-${Environment}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: patient-index
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: HIPAA
          Value: "true"
        - Key: Environment
          Value: !Ref Environment

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DentalScribeUsers-${Environment}
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DentalScribePatients-${Environment}
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      AttributeDefinitions:
        - AttributeName: practice_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: name_lowercase
          AttributeType: S
      KeySchema:
        - AttributeName: practice_id
          KeyType: HASH
        - AttributeName: patient_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: name-search-index
          KeySchema:
            - AttributeName: practice_id
              KeyType: HASH
            - AttributeName: name_lowercase
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # NEW: Templates Table
  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DentalScribeTemplates-${Environment}
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      AttributeDefinitions:
        - AttributeName: template_id
          AttributeType: S
      KeySchema:
        - AttributeName: template_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ========================================
  # SECRETS MANAGER
  # ========================================
  DeepgramSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub dental-scribe-deepgram-${Environment}
      Description: Deepgram API Key for speech-to-text
      SecretString: !Sub '{"api_key":"${DeepgramApiKey}"}'

  # ========================================
  # API GATEWAY
  # ========================================
  DentalScribeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub scribe32-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExistingUserPoolId}

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/scribe32-${Environment}
      RetentionInDays: 90

  # ========================================
  # LAMBDA FUNCTIONS
  # ========================================

  # Transcribe Audio Function
  TranscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-transcribe-${Environment}
      CodeUri: functions/transcribe/
      Handler: handler.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DeepgramSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /transcribe
            Method: POST

  # Generate SOAP Note Function
  GenerateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-generate-${Environment}
      CodeUri: functions/generate/
      Handler: handler.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          MODEL_ID: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-*
                - !Sub arn:aws:bedrock:*::foundation-model/anthropic.claude-*
                - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt DentalScribeNotesTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt TemplatesTable.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /generate-note
            Method: POST

  # Get Note History Function
  GetNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-history-${Environment}
      CodeUri: functions/notes/
      Handler: history.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DentalScribeNotesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /notes
            Method: GET

  # ========================================
  # TEMPLATES FUNCTIONS
  # ========================================
  
  # List & Create Templates
  TemplatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-templates-${Environment}
      CodeUri: functions/templates/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TemplatesTable
      Events:
        ListTemplates:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /templates
            Method: GET
        CreateTemplate:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /templates
            Method: POST

  # Get, Update, Delete Single Template
  TemplateByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-template-by-id-${Environment}
      CodeUri: functions/templates/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TemplatesTable
      Events:
        GetTemplate:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /templates/{template_id}
            Method: GET
        UpdateTemplate:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /templates/{template_id}
            Method: PUT
        DeleteTemplate:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /templates/{template_id}
            Method: DELETE

  # ========================================
  # PATIENT MANAGEMENT FUNCTIONS
  # ========================================

  # Search Patients Function
  SearchPatientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-search-patients-${Environment}
      CodeUri: functions/patients/
      Handler: search.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /patients/search
            Method: GET

  # Create Patient Function
  CreatePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-create-patient-${Environment}
      CodeUri: functions/patients/
      Handler: create.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /patients
            Method: POST

  # Get Patient Function
  GetPatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-get-patient-${Environment}
      CodeUri: functions/patients/
      Handler: get.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PatientsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /patients/{patient_id}
            Method: GET

  # ========================================
  # ADMIN FUNCTIONS
  # ========================================
  
  # Invite User Function
  InviteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-invite-${Environment}
      CodeUri: functions/admin/
      Handler: invite.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminGetUser
              Resource: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExistingUserPoolId}
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /admin/invite
            Method: POST

  # List Users Function
  ListUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scribe32-list-users-${Environment}
      CodeUri: functions/admin/
      Handler: list_users.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
                - cognito-idp:AdminGetUser
              Resource: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExistingUserPoolId}
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DentalScribeApi
            Path: /admin/users
            Method: GET

  # ========================================
  # CLOUDWATCH
  # ========================================
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub scribe32-errors-${Environment}
      AlarmDescription: Alert on Lambda errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
  # ========================================
  # CORS GATEWAY RESPONSES
  # ========================================
  Response4xx:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref DentalScribeApi

  Response5xx:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref DentalScribeApi

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${DentalScribeApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  UserPoolId:
    Description: Cognito User Pool ID (Existing)
    Value: !Ref ExistingUserPoolId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID (Existing)
    Value: !Ref ExistingUserPoolClientId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  NotesTableName:
    Description: DynamoDB Notes Table Name
    Value: !Ref DentalScribeNotesTable
    Export:
      Name: !Sub ${AWS::StackName}-NotesTable

  TemplatesTableName:
    Description: DynamoDB Templates Table Name
    Value: !Ref TemplatesTable
    Export:
      Name: !Sub ${AWS::StackName}-TemplatesTable
